kumuluzee:
  name: vzorcni-projekt
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/sense
      connection-url: jdbc:postgresql://manny.db.elephantsql.com:5432/soovegrb
      username: soovegrb
      password: I65GuuTJAqYJtWNoShB1hkoTmVftTrl3
      max-pool-size: 5
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      #data-source-health-check:
        #jndi-name: jdbc/sense
        #connection-url: jdbc:postgresql://manny.db.elephantsql.com:5432/soovegrb?user=soovegrb&password=I65GuuTJAqYJtWNoShB1hkoTmVftTrl3
      disk-space-health-check:
        treshold: 100000000
