kumuluzee:
  name: vzorcni-projekt
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/sense
      connection-url: jdbc:postgresql://manny.db.elephantsql.com:5432/soovegrb
      username: soovegrb
      password: WKQHRMQOqPvDSSGqYDmlXgsatJi4a9Oz
      max-pool-size: 5